package com.github.falchio.notes.data.errors

class NoAuthException: Throwable() {
}